# Generated by Django 6.1.1 on 2026-10-02 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetaLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normalized_name', models.CharField(max_length=100)),
                ('email_domain', models.CharField(max_length=100)),
                ('domain_key', models.CharField(max_length=100, unique=True)),
                ('region_email', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('beta_chefs_etablissement', models.PositiveIntegerField(default=0)),
                ('beta_enseignants', models.PositiveIntegerField(default=0)),
                ('beta_administration', models.PositiveIntegerField(default=0)),
                ('beta_inspecteurs', models.PositiveIntegerField(default=0)),
                ('beta_total', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'En cours'), ('success', 'Succès'), ('warning', 'Succès avec anomalies'), ('error', 'Erreur')], default='running', max_length=10)),
                ('number_of_records_fetched', models.PositiveIntegerField(default=0)),
                ('number_of_records_created', models.PositiveIntegerField(default=0)),
                ('number_of_records_updated', models.PositiveIntegerField(default=0)),
                ('anomalies', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('domain', models.CharField(db_index=True, max_length=100)),
                ('normalized_domain', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('academie', 'Académie'), ('regional', 'Région académique (multi-académies)'), ('national', 'National / opérateur'), ('non_apparie', 'Non apparié')], max_length=20)),
                ('cumulative_users', models.PositiveIntegerField()),
                ('cumulative_messages', models.PositiveIntegerField()),
                ('source_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='assistant_dashboard.betalocation')),
            ],
            options={
                'ordering': ['date', 'domain'],
                'constraints': [models.UniqueConstraint(fields=('date', 'domain'), name='unique_observation_date_domain')],
            },
        ),
    ]
