# Generated by Django 6.1.1 on 2026-10-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='betalocation',
            name='geo_shape',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
