# Generated by Django 6.1.1 on 2026-10-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_dashboard', '0002_beta_geo_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrun',
            name='status',
            field=models.CharField(choices=[('running', 'En cours'), ('success', 'Succès'), ('warning', 'Succès avec anomalies'), ('error', 'Erreur'), ('unchanged', 'Pas de nouvelle publication')], default='running', max_length=10),
        ),
    ]
