# Generated by Django 6.1.1 on 2026-10-03 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_dashboard', '0003_importrun_status_unchanged'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('school_year', models.CharField(max_length=9)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='assistant_dashboard.betalocation')),
            ],
            options={
                'ordering': ['location', 'start'],
                'constraints': [models.UniqueConstraint(fields=('location', 'description', 'start'), name='unique_holiday_period')],
            },
        ),
    ]
