# Generated by Django 6.1.1 on 2026-10-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_dashboard', '0004_school_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolholiday',
            name='zone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
